src/Admin/Controllers/LoginController.cs
using System.Threading.Tasks;
using Bit.Admin.Models;
using Bit.Core.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.Controllers
{
    public class LoginController : Controller
    {
        private readonly PasswordlessSignInManager<IdentityUser> _signInManager;

        public LoginController(
            PasswordlessSignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Index(string returnUrl = null, int? error = null, int? success = null,
            bool accessDenied = false)
        {
            if (!error.HasValue && accessDenied)
            {
                error = 4;
            }

            return View(new LoginModel
            {
                ReturnUrl = returnUrl,
                Error = GetMessage(error),
                Success = GetMessage(success)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                await _signInManager.PasswordlessSignInAsync(model.Email, model.ReturnUrl);
                return RedirectToAction("Index", new
                {
                    success = 3
                });
            }

            return View(model);
        }

        public async Task<IActionResult> Confirm(string email, string token, string returnUrl)
        {
            var result = await _signInManager.PasswordlessSignInAsync(email, token, true);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new
                {
                    error = 2
                });
            }

            if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", new
            {
                success = 1
            });
        }

        private string GetMessage(int? messageCode)
        {
            return messageCode switch
            {
                1 => "You have been logged out.",
                2 => "This login confirmation link is invalid. Try logging in again.",
                3 => "If a valid admin user with this email address exists, " +
                    "we've sent you an email with a secure link to log in.",
                4 => "Access denied. Please log in.",
                _ => null,
            };
        }
    }
}

src/Admin/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Bit.Admin.Models;
using Bit.Core;
using Bit.Core.Models.Table;
using Bit.Core.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Bit.Admin.Controllers
{
    [Authorize]
    [SelfHosted(NotSelfHostedOnly = true)]
    public class ToolsController : Controller
    {
        private readonly GlobalSettings _globalSettings;
        private readonly IOrganizationRepository _organizationRepository;
        private readonly IOrganizationService _organizationService;
        private readonly IUserService _userService;
        private readonly ITransactionRepository _transactionRepository;
        private readonly IInstallationRepository _installationRepository;
        private readonly IOrganizationUserRepository _organizationUserRepository;
        private readonly IPaymentService _paymentService;
        private readonly ITaxRateRepository _taxRateRepository;

        public ToolsController(
            GlobalSettings globalSettings,
            IOrganizationRepository organizationRepository,
            IOrganizationService organizationService,
            IUserService userService,
            ITransactionRepository transactionRepository,
            IInstallationRepository installationRepository,
            IOrganizationUserRepository organizationUserRepository,
            ITaxRateRepository taxRateRepository,
            IPaymentService paymentService)
        {
            _globalSettings = globalSettings;
            _organizationRepository = organizationRepository;
            _organizationService = organizationService;
            _userService = userService;
            _transactionRepository = transactionRepository;
            _installationRepository = installationRepository;
            _organizationUserRepository = organizationUserRepository;
            _taxRateRepository = taxRateRepository;
            _paymentService = paymentService;
        }

        public IActionResult ChargeBraintree()
        {
            return View(new ChargeBraintreeModel());
        }

        [HttpPost]
        public async Task<IActionResult> ChargeBraintree(ChargeBraintreeModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var btGateway = new Braintree.BraintreeGateway
            {
                Environment = _globalSettings.Braintree.Production ?
                    Braintree.Environment.PRODUCTION : Braintree.Environment.SANDBOX,
                MerchantId = _globalSettings.Braintree.MerchantId,
                PublicKey = _globalSettings.Braintree.PublicKey,
                PrivateKey = _globalSettings.Braintree.PrivateKey
            };

            var btObjIdField = model.Id[0] == 'o' ? "organization_id" : "user_id";
            var btObjId = new Guid(model.Id.Substring(1, 32));

            var transactionResult = await btGateway.Transaction.SaleAsync(
                new Braintree.TransactionRequest
                {
                    Amount = model.Amount.Value,
                    CustomerId = model.Id,
                    Options = new Braintree.TransactionOptionsRequest
                    {
                        SubmitForSettlement = true,
                        PayPal = new Braintree.TransactionOptionsPayPalRequest
                        {
                            CustomField = $"{btObjIdField}:{btObjId}"
                        }
                    },
                    CustomFields = new Dictionary<string, string>
                    {
                        [btObjIdField] = btObjId.ToString()
                    }
                });

            if (!transactionResult.IsSuccess())
            {
                ModelState.AddModelError(string.Empty, "Charge failed. " +
                    "Refer to Braintree admin portal for more information.");
            }
            else
            {
                model.TransactionId = transactionResult.Target.Id;
                model.PayPalTransactionId = transactionResult.Target?.PayPalDetails?.CaptureId;
            }
            return View(model);
        }

        public IActionResult CreateTransaction(Guid? organizationId = null, Guid? userId = null)
        {
            return View("CreateUpdateTransaction", new CreateUpdateTransactionModel
            {
                OrganizationId = organizationId,
                UserId = userId
            });
        }

        [HttpPost]
        public async Task<IActionResult> CreateTransaction(CreateUpdateTransactionModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateUpdateTransaction", model);
            }

            await _transactionRepository.CreateAsync(model.ToTransaction());
            if (model.UserId.HasValue)
            {
                return RedirectToAction("Edit", "Users", new { id = model.UserId });
            }
            else
            {
                return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId });
            }
        }

        public async Task<IActionResult> EditTransaction(Guid id)
        {
            var transaction = await _transactionRepository.GetByIdAsync(id);
            if (transaction == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("CreateUpdateTransaction", new CreateUpdateTransactionModel(transaction));
        }

        [HttpPost]
        public async Task<IActionResult> EditTransaction(Guid id, CreateUpdateTransactionModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateUpdateTransaction", model);
            }
            await _transactionRepository.ReplaceAsync(model.ToTransaction(id));
            if (model.UserId.HasValue)
            {
                return RedirectToAction("Edit", "Users", new { id = model.UserId });
            }
            else
            {
                return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId });
            }
        }

        public IActionResult PromoteAdmin()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PromoteAdmin(PromoteAdminModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var orgUsers = await _organizationUserRepository.GetManyByOrganizationAsync(
                model.OrganizationId.Value, null);
            var user = orgUsers.FirstOrDefault(u => u.UserId == model.UserId.Value);
            if (user == null)
            {
                ModelState.AddModelError(nameof(model.UserId), "User Id not found in this organization.");
            }
            else if (user.Type != Core.Enums.OrganizationUserType.Admin)
            {
                ModelState.AddModelError(nameof(model.UserId), "User is not an admin of this organization.");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            user.Type = Core.Enums.OrganizationUserType.Owner;
            await _organizationUserRepository.ReplaceAsync(user);
            return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId.Value });
        }

        public IActionResult GenerateLicense()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GenerateLicense(LicenseModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = null;
            Organization organization = null;
            if (model.UserId.HasValue)
            {
                user = await _userService.GetUserByIdAsync(model.UserId.Value);
                if (user == null)
                {
                    ModelState.AddModelError(nameof(model.UserId), "User Id not found.");
                }
            }
            else if (model.OrganizationId.HasValue)
            {
                organization = await _organizationRepository.GetByIdAsync(model.OrganizationId.Value);
                if (organization == null)
                {
                    ModelState.AddModelError(nameof(model.OrganizationId), "Organization not found.");
                }
                else if (!organization.Enabled)
                {
                    ModelState.AddModelError(nameof(model.OrganizationId), "Organization is disabled.");
                }
            }
            if (model.InstallationId.HasValue)
            {
                var installation = await _installationRepository.GetByIdAsync(model.InstallationId.Value);
                if (installation == null)
                {
                    ModelState.AddModelError(nameof(model.InstallationId), "Installation not found.");
                }
                else if (!installation.Enabled)
                {
                    ModelState.AddModelError(nameof(model.OrganizationId), "Installation is disabled.");
                }
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (organization != null)
            {
                var license = await _organizationService.GenerateLicenseAsync(organization,
                    model.InstallationId.Value, model.Version);
                return File(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(license, Formatting.Indented)),
                    "text/plain", "bitwarden_organization_license.json");
            }
            else if (user != null)
            {

src/Admin/Views/Shared/_BillingInformation.cshtml
@model BillingInformationModel
<dl class="row">
    <dt class="col-sm-4 col-lg-3">Account @(Model.BillingInfo.Balance <= 0 ? "Credit" : "Balance")</dt>
    <dd class="col-sm-8 col-lg-9">@Math.Abs(Model.BillingInfo.Balance).ToString("C")</dd>

    <dt class="col-sm-4 col-lg-3">Invoices</dt>
    <dd class="col-sm-8 col-lg-9">
        @if(Model.BillingInfo.Invoices?.Any() ?? false)
        {
            <table class="table">
                <tbody>
                    @foreach(var invoice in Model.BillingInfo.Invoices)
                    {
                        <tr>
                            <td>@invoice.Date</td>
                            <td><a target="_blank" href="@invoice.Url" title="View Invoice">@invoice.Number</a></td>
                            <td>@invoice.Amount.ToString("C")</td>
                            <td>@(invoice.Paid ? "Paid" : "Unpaid")</td>
                            <td>
                                <a target="_blank" href="@invoice.PdfUrl" title="Download Invoice">
                                    <i class="fa fa-file-pdf-o"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            @: No invoices.
        }
    </dd>

    <dt class="col-sm-4 col-lg-3">Transactions</dt>
    <dd class="col-sm-8 col-lg-9">
        @if(Model.BillingInfo.Transactions?.Any() ?? false)
        {
            <table class="table">
                <tbody>
                    @foreach(var transaction in Model.BillingInfo.Transactions)
                    {
                        <tr>
                            <td>@transaction.CreatedDate</td>
                            <td>@transaction.Type.ToString()</td>
                            <td>@transaction.PaymentMethodType.ToString()</td>
                            <td>@transaction.Details</td>
                            <td>@transaction.Amount.ToString("C")</td>
                            <td>
                                <a title="Edit Transaction" asp-controller="Tools" asp-action="EditTransaction"
                                   asp-route-id="@transaction.Id"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No transactions.</p>
        }
        <a asp-action="CreateTransaction" asp-controller="Tools" asp-route-organizationId="@Model.OrganizationId"
           asp-route-userId="@Model.UserId" class="btn btn-sm btn-outline-primary">
            <i class="fa fa-plus"></i> New Transaction
        </a>
    </dd>
</dl>

src/Admin/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager
@inject Bit.Core.Settings.GlobalSettings GlobalSettings
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex,nofollow" />
    <title>@ViewData["Title"] - Bitwarden Admin Portal</title>

    <link rel="stylesheet" href="~/css/webfonts.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <i class="fa fa-lg fa-fw fa-shield"></i> Admin
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    @if(SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item" active-controller="Users">
                            <a class="nav-link" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item" active-controller="Organizations">
                            <a class="nav-link" asp-controller="Organizations" asp-action="Index">Organizations</a>
                        </li>
                        @if(!GlobalSettings.SelfHosted)
                        {
                            <li class="nav-item dropdown" active-controller="tools">
                                <a class="nav-link dropdown-toggle" href="#" id="toolsDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Tools
                                </a>
                                <div class="dropdown-menu" aria-labelledby="toolsDropdown">
                                    <a class="dropdown-item" asp-controller="Tools" asp-action="ChargeBraintree">
                                        Charge Braintree Customer
                                    </a>
                                    <a class="dropdown-item" asp-controller="Tools" asp-action="CreateTransaction">
                                        Create Transaction
                                    </a>
                                    <a class="dropdown-item" asp-controller="Tools" asp-action="PromoteAdmin">
                                        Promote Admin
                                    </a>
                                    <a class="dropdown-item" asp-controller="Tools" asp-action="GenerateLicense">
                                        Generate License
                                    </a>
                                    <a class="dropdown-item" asp-controller="Tools" asp-action="TaxRate">
                                        Manage Tax Rates
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item" active-controller="Logs">
                                <a class="nav-link" asp-controller="Logs" asp-action="Index">Logs</a>
                            </li>
                        }
                    }
                    @if(GlobalSettings.SelfHosted)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="https://help.bitwarden.com/hosting/" target="_blank">Docs</a>
                        </li>
                    }
                </ul>
                @if(SignInManager.IsSignedIn(User))
                {
                    <form asp-controller="Login" asp-action="Logout" method="post">
                        <button type="submit" class="btn btn-sm btn-secondary">Log Out</button>
                    </form>
                }
                else
                {
                    <a class="btn btn-sm btn-secondary" asp-controller="Login" asp-action="Index">Log In</a>
                }
            </div>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>

    <footer class="container mb-4">
        <hr />
        &copy; @DateTime.Now.Year, Bitwarden Inc.
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.slim.js"></script>
        <script src="~/lib/popper/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.slim.min.js" asp-append-version="true"></script>
        <script src="~/lib/popper/popper.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>